[package]
name = "litua"
version = "0.1.0"
edition = "2021"

[dependencies]
mlua = { version = "0.7", features = ["lua54", "vendored"] }
anyhow = "1.0"
clap = { version = "4.0.27", features = ["derive"] }
